_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 5
                - 6
                - 53
                - 55
            "2":
                - 5
                - 6
                - 53
                - 55
            "3":
                - 2
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
